### ISSUE TITLE
Server not being blacklisted on timeout

### ISSUE THREAD

**Issue by bleonard** [instacart/makara#102]
My hypothesis is that the unicorn (or something upstream) has a timeout shorter than the timeout being used by the db gem (mysql2).

I'm investigating what these settings do and what happens when I set them and if makara handles it appropriately.

```
production:
  connect_timeout: 1
  read_timeout: 1
  write_timeout: 1
  checkout_timeout: 1
```

@sax @Drakula2k does the postgres AR gem have similar settings?
