### ISSUE TITLE
Defining host in top-level database.yml config

### ISSUE THREAD

**Issue by amhuntsman** [instacart/makara#129]
This is a fairly minor thing, but it led to some confusion before looking at the README more carefully. The example database.yml instructs filling in "any other standard AR configurations" but doesn't demonstrate defining `host` in that spot. To new users like us, it may appear this isn't needed since the hosts are defined in the ensuing `makara` block. However, omitting the top-level host leads to unexpected errors, as we discovered when running migrations.

Is it feasible to set this value programmatically from the makara config, or otherwise add this caveat to the README?

**Comment by bleonard** [comment]
what errors were you seeing and what's your database.yml config?

**Comment by amhuntsman** [comment]
database.yml looks like this:

``` yaml
default: &default
  adapter: postgresql_makara
  encoding: unicode
  username: username
  password: password
  makara:
    blacklist_duration: 5
    master_ttl: 5
    master_strategy: failover
    sticky: true
    connections:
      - role: master
        host: 192.168.1.1
      - role: slave
        host: 192.168.1.2

development: &development
  <<: *default
  database: example_dev
```

Error from running rake db:migrate...

```
pg_dump: [archiver (db)] connection to database "example_dev" failed: FATAL:  role "username" does not exist
rake aborted!
Error dumping database
/Users/user/.rbenv/versions/2.0.0-p643/bin/bundle:23:in `load'
/Users/user/.rbenv/versions/2.0.0-p643/bin/bundle:23:in `<main>'
Tasks: TOP => db:structure:dump
(See full trace by running task with --trace)
```

We believe this is happening in the schema dump portion of the migration, which is running pg_dump on the local machine rather than where the development DB lives. It can't find the proper host unless it's defined at the top level of the database configuration. Adding a `host` entry above the `makara` block fixes the issue.

https://github.com/rails/rails/blob/v4.0.11/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L82
