### ISSUE TITLE
Site is down when master is ok and slave is down

### ISSUE THREAD

**Issue by Tonkonozhenko** [instacart/makara#130]
Hi!

Issue is that when master is ok but slave is down whole site is down.

I have such initializer to perform some operations from slave and all other from master:

``` ruby
# https://github.com/ankane/shorts/blob/master/Scaling-Reads.md

Makara::Cache.store = :noop

module DefaultToMasterPool
  def _appropriate_pool(*args)
    return @master_pool unless Thread.current[:distribute_reads]
    super
  end
end

Makara::Proxy.prepend DefaultToMasterPool

module DistributeReads
  def distribute_reads
    previous_value = Thread.current[:distribute_reads]
    begin
      Thread.current[:distribute_reads] = true
      Makara::Context.set_current(Makara::Context.generate)
      yield
    ensure
      Thread.current[:distribute_reads] = previous_value
    end
  end
end

Object.include DistributeReads
```

and makara config:

``` yaml
common: &common
  adapter: mysql2_makara
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  pool: 30
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *common
  database: production

  makara:
    sticky: true
    connections:
      - role: master
        host: sql01.production
      - role: slave
        host: sql02.production

```

**Comment by bleonard** [comment]
Makara is deciding between master and slave and using that. If it decides to the slave, it's going to just use it. and if it crashes, then it's going to fail.

One solution would be to add the master db (often with a read-only) user to the slave pool.

``` yaml
common: &common
  adapter: mysql2_makara
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  pool: 30
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *common
  database: production

  makara:
    sticky: true
    slave_strategy: failover
    connections:
      - role: master
        host: sql01.production
      - role: slave
        host: sql02.production
      - role: slave
        host: sql01.production
```

In the above, I added the same host to the slave pool. By doing _just_ that they would defualt to round robin between the two. It sounded like you want to only use the master as a slave in the case of slave failure. So I added `failover` as the slave strategy as well.

**Comment by bleonard** [comment]
let me know if this doesn't work for you and reopen.

**Comment by bleonard** [comment]
As a side note, it look like you might be able to use `without_sticking` instead of the thread variable and the inject of `DefaultToMasterPool`

``` ruby
module DistributeReads
  def distribute_reads
    ActiveRecord::Base.connection.without_sticking do
      yield
    end
  end
end
```

**Comment by palexvs** [comment]
@bleonard,  It could work, but how to say to use master by default in a whole Rails 5.1.4 application?

`ActiveRecord::Base.connection.stick_to_master!` does not work, as I understand I should say `stick_to_master!` to all connections in the pool. How to do it?

Thank you

**Comment by bleonard** [comment]
I'm not sure I fully understand the goal. Maybe you want to use master for your reads by default, but if there is an issue failover to a slave?

If that is the case, it's all about the order of your yml file and the strategy.
If you put the master node in the `slave` section at the top and use `slave_strategy: failover` then it will have that effect.

**Comment by palexvs** [comment]
Hi, @bleonard 
I want to always read from `master` except situation when I explicitly say to read from `slave`. Currently, we do it using:

`config/initializers/makara.rb`:
```
# https://github.com/ankane/shorts/blob/master/Scaling-Reads.md

Makara::Cache.store = :noop

module DefaultToMasterPool
  def _appropriate_pool(*args)
    return @master_pool unless Thread.current[:distribute_reads]
    super
  end
end

Makara::Proxy.prepend DefaultToMasterPool

module DistributeReads
  def distribute_reads
    previous_value = Thread.current[:distribute_reads]
    begin
      Thread.current[:distribute_reads] = true
      Makara::Context.set_current(Makara::Context.generate)
      yield
    ensure
      Thread.current[:distribute_reads] = previous_value
    end
  end
end

Object.include DistributeReads
```

`/config/database.yml`:
```
common: &common
  adapter: mysql2_makara
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  pool: 30
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *common
  database: production

  makara:
    sticky: true
    slave_strategy: failover
    connections:
      - role: master
        host: sql01.production
      - role: slave
        host: sql02.production
      - role: slave
        host: sql01.production
```

`controller`:
```
...
  Site.find(id) # always reads from master

  distribute_reads do # explicitly reads from master
   Site.find(id)
  end
```


And it works. But I'm trying to figure out how to make it simpler with your suggestion:
```
As a side note, it looks like you might be able to use without_sticking instead of the thread variable and the inject of DefaultToMasterPool

module DistributeReads
  def distribute_reads
    ActiveRecord::Base.connection.without_sticking do
      yield
    end
  end
end
```

But when I remove `DefaultToMasterPool` all read queries go to `slave`

Thank you
