### ISSUE TITLE
Prolonged DB migrations

### ISSUE THREAD

**Issue by quekshuy** [instacart/makara#137]
We've found that running `rake db:migrate` takes an inordinately long amount of time when using makara vs without it.

Here's our database.yml file (only the relevant block):

``` yml
staging:
  adapter: 'postgresql_makara'
  encoding: utf8
  reconnect: false
  database: db_staging
  pool: 5
  username: my_username
  password: my_password
  host: 10.0.0.6
  port: 5432
  prepared_statements: false
  makara:
    connections:
      - role: master
        blacklist_duration: 0
        disable_blacklist: true
        host: 10.0.0.6
        port: 5432
      - role: slave
        host: 10.0.0.5
        port: 5432
```

Could `prepared_statements: false` be messing with it. Or are there options that we're missing, e.g. `master_ttl`, etc.
