### ISSUE TITLE
NoMethodError: undefined method `map' for nil:NilClass when attempting to run db:seed

### ISSUE THREAD

**Issue by gregorybilello** [instacart/makara#167]
Trying to run:

`bundle exec rake db:seed`

in a production database, but getting the following error and trace:

`rake aborted!
NoMethodError: undefined method 'map' for nil:NilClass
/home/deploy/.rvm/gems/ruby-2.1.5/gems/makara-0.3.7/lib/makara/config_parser.rb:177:in 'all_configs'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/makara-0.3.7/lib/makara/config_parser.rb:161:in 'master_configs'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/makara-0.3.7/lib/makara/proxy.rb:271:in 'instantiate_connections'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/makara-0.3.7/lib/makara/proxy.rb:57:in 'initialize'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/makara-0.3.7/lib/active_record/connection_adapters/makara_abstract_adapter.rb:139:in 'initialize'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/makara-0.3.7/lib/active_record/connection_adapters/mysql2_makara_adapter.rb:9:in 'new'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/makara-0.3.7/lib/active_record/connection_adapters/mysql2_makara_adapter.rb:9:in 'mysql2_makara_connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in 'new_connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in 'checkout_new_connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in 'acquire_connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in 'block in checkout'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in 'checkout'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in 'block in connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in 'connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in 'retrieve_connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_handling.rb:113:in 'retrieve_connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/connection_handling.rb:87:in 'connection'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/migration.rb:909:in 'initialize'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/migration.rb:822:in 'new'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/migration.rb:822:in 'open'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/railties/databases.rake:157:in 'block (2 levels) in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.7/lib/active_record/railties/databases.rake:173:in 'block (2 levels) in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.1.5/gems/rake-11.2.2/exe/rake:27:in '<top (required)>'
/home/deploy/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in 'eval'
/home/deploy/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in '<main>'`

The seed file doesn't appear to have any syntax errors, as I ran it locally and it worked fine.

Any idea what could be causing the issue?

**Comment by bleonard** [comment]
you are missing the `connections` array in our database.yml.
There are changes to make in the format from the old one you had before makara.
Example.

```
production:
  adapter: 'mysql2_makara'
  database: 'MyAppProduction'
  # any other standard AR configurations

  # add a makara subconfig
  makara:

    # the following are default values
    blacklist_duration: 5
    master_ttl: 5
    master_strategy: round_robin
    sticky: true

    # list your connections with the override values (they're merged into the top-level config)
    # be sure to provide the role if master, role is assumed to be a slave if not provided
    connections:
      - role: master
        host: master.sql.host
      - role: slave
        host: slave1.sql.host
      - role: slave
        host: slave2.sql.host
```

**Comment by gregorybilello** [comment]
Had the connections array in our database.yml file.  Here's a sanitized version of that file:
```
default: &default
  adapter: mysql2_makara
  encoding: utf8
  reconnect: true
  pool: 5

development:
  <<: *default
  database: dev_database
  username: dev_username
  password: dev_password
  port: 3333
  host: hostname

test:
  <<: *default
  database: test_database

production:
  <<: *default
  makara:
    # the following are default values
    blacklist_duration: 5
    master_ttl: 1
    master_strategy: round_robin
    sticky: false

    connections:
      - role: master
        host: hostname
        database: prod_database
        port: 3333
        username: username
        password: password
        blacklist_duration: 5

      - role: slave
        database: prod_database
        port: 3333
        host: hostname
        username: username
        password: password
```

Is there anything we're missing?
