### ISSUE TITLE
All slaves down, but no fallback to the master

### ISSUE THREAD

**Issue by darksoul42** [instacart/makara#186]
I have a Redmine cluster with one master and two slaves running Postgres 9.5 on FreeBSD servers, and everything works as expected when everything is up. (Updates go to the master, selects go to the slave)

However, if one slave node goes down, I get a set_client_encoding error (though I suspect this is due to how the "pg" gem handles its own errors), and this does not happen when not defining "encoding". I could get that "invalid encoding error" to be gracefully handled, but this only revealed an underlying issue.

If both nodes are down or blacklisted, it seems 0.3.9 never falls back to the master, and retries forever only on the slaves, leading to an application timeout, meaning things do not work as advertised in the README.

I was wondering if there shouldn't be a tunable to say whether one wants to fallback to the master or not? I did look in the source code but could not find it.

(Also, as a side-note, if the master is down, given that Redmine requires updating stuff like authentication tokens, only having a slave alive is not enough)

Here is my database.yml :
```
production:
  adapter: postgresql_makara
  database: redmine
  username: redmine
  encoding: utf-8
  pool: 10
  makara:
    master_ttl: 10
    sticky: true
    connections:
      - role: master
        host: master.host
      - role: slave
        host: slave1.host
      - role: slave
        host: slave2.host
    connection_error_matchers:
      - '/invalid encoding name/'
```
