### ISSUE TITLE
It doesn't send a query to master. Why so? 🤔

### ISSUE THREAD

**Issue by artkirienko** [instacart/makara#205]
https://github.com/taskrabbit/makara#common-problems--solutions

**database.yml**
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: postgres
  username: postgres

development:
  adapter: 'postgresql_makara'
  encoding: unicode
  pool: 10
  database: jiffyshirts_development
  makara:
    id: postgresql
    blacklist_duration: 5
    master_ttl: 5
    master_strategy: round_robin
    slave_strategy: round_robin
    sticky: false
    connections:
      - role: master
        blacklist_duration: 0
        url: 'postgres://postgres@postgres:5432/jiffyshirts_development'
      - role: slave
        url: 'postgres://postgres@postgres:5432/jiffyshirts_replica'

test:
  database: jiffyshirts_test
  <<: *default

deploy:
  database: jiffyshirts_development
  <<: *default
```

1. It uses slave database. It's okay.
```ruby
> Spree::User.last
  [slave/1] Spree::User Load (1.5ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL  ORDER BY "spree_users"."id" DESC LIMIT 1
```

2. It is still using slave database. Why so? I've even tried to set **master_ttl** to **600**. Same problem.
```ruby
> Spree::User.connection.stick_to_master!(true); Spree::User.last
  [slave/1] Spree::User Load (1.2ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL  ORDER BY "spree_users"."id" DESC LIMIT 1
```
