### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::IndeterminateDatatype

### ISSUE THREAD

**Issue by chadwilken** [instacart/makara#213]
I am using makara with the makara_postgis adapter and after deploying to production I kept getting `ActiveRecord::StatementInvalid: PG::IndeterminateDatatype ERROR:  could not determine data type of parameter $1` for simple `SELECT` statements like `SELECT * from companies WHERE id = $1` and then a integer id.

I am using Rails 5.2.0 with makara 0.4.0 with Postgis running on RDS and connections through PgBouncer.

**Comment by chadwilken** [comment]
I’m not sure how, but this seems to have self resolved.

**Comment by GaudamThiyagarajan** [comment]
@chadwilken  can you give a sample config of how you established pgbouncer with makara

**Comment by chadwilken** [comment]
@GaudamThiyagarajan you just set your database URLs to your pgbouncer URL. The URL *has* to have the protocol, username, password, URL, port, and database name to work with Makara. You must also disable prepared_statments.

```
default: &default
  adapter: makara_postgis
  prepared_statements: false
  postgis_extension: true
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV['IDLE_TIMEOUT'] || 300 %>
  checkout_timeout: <%= ENV['CHECKOUT_TIMEOUT'] || 5 %>
  schema_search_path: public, tiger

production:
  <<: *default
  makara:
    id: postgres
    connections:
      - role: master
        url: 'postgres://username:password@localhost:5432/your_db'
      - role: slave
        url: 'postgres://username:password@localhost:5432/your_db_replica'
```
