### ISSUE TITLE
Statement timeout

### ISSUE THREAD

**Issue by chadwilken** [instacart/makara#214]
Using default AR you can set variables in the database.yml config for statement_timeout and other pg items, is there a way to make it work with Makara? In my testing Makara seems to ignore all but a few standard keys.

**Comment by chadwilken** [comment]
Still curious about this if anyone has an answer

**Comment by bleonard** [comment]
It should pas through the normal `pg` ones through to the Postgres adapter.

```
production:
  adapter: 'pg_makara'
  database: 'MyAppProduction'
  # any other standard AR configurations

  # add a makara subconfig
  makara:

    # optional id to identify the proxy with this configuration for stickiness
```
