### ISSUE TITLE
My app crash when any replica goes down.

### ISSUE THREAD

**Issue by fmundaca** [instacart/makara#216]
Hello, maybe this is a duplicate issue but after some little research in the issue section i can't find any help. 

We have an API in rails 4.2 living in Elastic Beanstalk connected to a Postgres 9.4 DB running on AWS RDS with a master-slave configuration. 1 master and 2 slaves. When any of my two replicas goes down the api can't recover their health and make a crush.

My Makara version is 0.4.0 and this is my database.yml
```YML
default: &default
 pool: 50
 timeout: 5000


staging:
 <<: *default
 adapter: postgresql_makara
 host: <%= ENV['RDS_HOSTNAME'] %>
 database: <%= ENV['RDS_DB_NAME'] %>
 password: <%= ENV['RDS_PASSWORD'] %>
 username: <%= ENV['RDS_USERNAME'] %>
 reconnect: true
 makara:
    blacklist_duration: 30
    master_ttl: 5
    master_strategy: round_robin
    slave_strategy: round_robin
    sticky: true
    rescue_connection_failures: true
    connection_error_matchers:
      - '/PG::ConnectionBad:/'
      - !ruby/regexp '/pg::error: : select/'
      - !ruby/regexp '/no more connections allowed/'
      - !ruby/regexp '/result has been cleared/'
      - !ruby/regexp '/no connection to the server/'
      - !ruby/regexp '/the database system is (starting up|shutting down)/'
      - !ruby/regexp '/reset has failed/'
      - !ruby/regexp '/connection not open/i'
    connections:
    - role: master
      host: <%= ENV['RDS_MASTER_HOSTNAME'] %>
      name: 'rankmi-staging-master'
    - role: slave
      host: <%= ENV['RDS_SLAVE_HOSTNAME'] %>
      weight: 5
      name: 'rankmi-staging-replica-1'
    - role: slave
      host: <%= ENV['RDS_SLAVE_SMALL_HOSTNAME'] %>
      weight: 5
      name: 'rankmi-staging-replica-2'
```

any help would be very appreciated 

thanks!
