### ISSUE TITLE
All connections are blacklisted -> No error details

### ISSUE THREAD

**Issue by Yaroslav-F** [instacart/makara#221]
Morning!

Very quick question/issue here.
I've tried switching from mysql to makara adapter in `database.yml` and all seemed to work fine at first.
```
production:
  database: *****
  pool: **
  username: ****
  adapter: mysql2_makara
  makara:
    id: prod
    sticky: true
    connections:
      - role: master
        host: production.master.rds.com
        name: MasterNode
      - role: slave
        host: production.master.rds.com
        name: ReadReplica
```
_Please note that I'm using same host for master and slave for now until I can get read replica up and running._

Then I noticed that for operations on some objects, where object is locked (selected for update) for longer period of time - makara blacklists all connections and raises `[Makara/master] All connections are blacklisted -> No error details` error.

So far I dealt with it by adding `disable_blacklist: true` flag to my master connection portion of config. However I'd like to understand why connections are getting blacklisted, is that because of the delay caused by locking the object? Or by the fact that both master & slave are pointing to the same host?

Could someone clear things out for me please?
Many Thanks!
