### ISSUE TITLE
[Question] Aurora Reader Endpoint + Makara

### ISSUE THREAD

**Issue by Yaroslav-F** [instacart/makara#227]
Hello there,

I had an interesting case last night which prompts a question.
I'm using Makara with AWS Aurora Mysql adapter:
```
staging:
  encoding: utf8
  database: xxxxxxx
  pool: 25
  username: xxxxxx
  password: xxxxxx
  xa: false
  adapter: mysql2_makara
  makara:
    id: my_prod_db
    sticky: true
    connections:
      - role: master
        host: aurora.writer-endpoint.com
        name: MasterNode
        disable_blacklist: true
      - role: slave
        host: aurora.reader-cluster-endpoint.com
        name: ReadReplica
```

in the snippet above `aurora.reader-cluster-endpoint.com` is [Aurora read cluster](https://aws.amazon.com/blogs/aws/new-reader-endpoint-for-amazon-aurora-load-balancing-higher-availability/) endpoint which scales automatically and balances database connections as they come in.

I tested this config last night under heavy load and it does not seem to be balancing out, CPU utilization on the newly spawned Read Replica is pretty low:
![image](https://user-images.githubusercontent.com/4863615/51381756-e827f100-1b0c-11e9-80a4-a66e7f761758.png)

And I'm pretty sure this is the case because of the persisting connections from the app to the original overloaded Read Replica. Connections graph for the same time:
![image](https://user-images.githubusercontent.com/4863615/51381968-77350900-1b0d-11e9-9242-193f399d5178.png)

So my question is: is it possible to tell makara to obtain a new database connection for slaves every time? Ideally I'm looking for a wrapper for the block of code (that does massive select statements) which will obtain new connection every time it's run.
