### ISSUE TITLE
Makara Harshly Handling a Validation Error

### ISSUE THREAD

**Issue by tmedford** [instacart/makara#228]
Why does Makara harshly handle a validation error. A connection should not be blacklisting based on validation.

![image](https://user-images.githubusercontent.com/4482381/53349631-8583fb00-38eb-11e9-99f1-56c6921e0054.png)

![image](https://user-images.githubusercontent.com/4482381/53349553-59687a00-38eb-11e9-8586-e814042981a0.png)

![image](https://user-images.githubusercontent.com/4482381/53349464-26be8180-38eb-11e9-9eaf-cfa1a1d5ec02.png)

**Comment by wxwang33** [comment]
+1

**Comment by tmedford** [comment]
Any update on this.

**Comment by rosa** [comment]
@tmedford I'm sorry, I'm not sure I follow. Harshly handled errors don't cause a blacklisted connection, gracefully handled errors do:
https://github.com/taskrabbit/makara/blob/7f6e9d0c1a8be6ff73b630f2092894a6556ff046/lib/makara/error_handler.rb#L26-L36

**Comment by tmedford** [comment]
@rosa Then why do we see a error log message in logs?

**Comment by rosa** [comment]
@tmedford because it's an error, and it's raised as such. What you see in your logs comes from here:
```ruby
def harshly(e) 
   ::Makara::Logging::Logger.log("Harshly handling: #{e}\n#{e.backtrace.join("\n\t")}") 
   raise e 
end
```
But no connection is blacklisted as result of it.

**Comment by capripot** [comment]
I experience that problem in a slightly difference way.

**Context**
Sinatra app with ActiveRercord 4. Sinatra app rescues ActiveRecord::RecordInvalid errors.

**Problem**
With Makara in place, `ActiveRecord::RecordInvalid` errors gets wrapped into a `Makara::Errors::BlacklistConnection` error because it handled "gracefully" in the [`MakaraAbstractAdapter`](https://github.com/taskrabbit/makara/blob/master/lib/active_record/connection_adapters/makara_abstract_adapter.rb#L47) then in turn wrapped into [Makara::Errors::AllConnectionsBlacklisted](https://github.com/taskrabbit/makara/blob/master/lib/makara/pool.rb#L118).

**Solution**
I think by default, `ActiveRecord::RecordInvalid` shlould be handled harshly, what do you all think?

**Comment by psahni** [comment]
@rosa  - How to handle blacking issue
'Makara::Errors::AllConnectionsBlacklisted: [Makara/slave] All connections are blacklisted -> No error details'

```
  makara:
      id: postgresql
      sticky: true
      blacklist_duration: 5
      master_ttl: 5
      master_strategy: round_robin
      slave_strategy: failover # Keep the same until it is blacklisted
      # list your connections with the override values (they're merged into the top-level config)
      # be sure to provide the role if primary, role is assumed to be a replica if not provided
      connections:
        - role: master
          name: master
          host: <%= ENV['DB_HOST'] %>
          disable_blacklist: true
        #### implicit role: slave
        - name: replica1
          host: <%= ENV['DB_HOST_REPLICA_1'] %>
        - name: replica2
          host: <%= ENV['DB_HOST_REPLICA_2'] %>
        - name: replica3
          host: <%= ENV['DB_HOST_REPLICA_3'] %>
```
