### ISSUE TITLE
[Makara] No connections are available in the slave pool

### ISSUE THREAD

**Issue by fmluizao** [instacart/makara#230]
I'm feeling very stupid to ask this, but can't get makara to work...
This is my database.yml

```
production:
  adapter: postgresql_makara
  username: pguser
  password: pgpass
  database: pgdb

  makara:
    connections:
      - role: master
        host: 'postgresql://pguser:pgpass@master-ip/pgdb'
      - role: slave
        host: 'postgresql://pguser:pgpass@slave-ip/pgdb'
```

If I open a rails console, and try to fetch something, I get:

```
> SomeModel.first
> Makara::Errors::NoConnectionsAvailable ([Makara] No connections are available in the slave pool)
```

I can connect directly to both databases, the following works normally:

```
production:
  adapter: postgresql
  username: pguser
  password: pgpass
  database: pgdb
  host: master-ip (or slave-ip)
```

I'm using Rails 5.2.2, Ruby 2.6.1.

What I'm doing wrong?

**Comment by fmluizao** [comment]
Figured out. I was specifying connection string in the **host** field, when it was to use the **url** field under **connections**. Correct database.yml:
```
production:
  adapter: postgresql_makara
  username: pguser
  password: pgpass
  database: pgdb

  makara:
    connections:
      - role: master
        host: master-ip
        url: 'postgresql://pguser:pgpass@master-ip/pgdb'
      - role: slave
        host: slave-ip
        url: 'postgresql://pguser:pgpass@slave-ip/pgdb'
```
