### ISSUE TITLE
In Rails: Makara doesn't appear to support `rake db:structure:dump`

### ISSUE THREAD

**Issue by jjthrash** [instacart/makara#245]
I don't consider this an important issue, nor possibly even an issue with Makara? but it should be documented for search engines.

## Problem

Running `bundle exec rake db:structure:dump` leads to a confusing error.

```
user@machine:~/app_path$ RAILS_ENV=production bundle exec rake db:migrate
pg_dump: [archiver (db)] connection to database "databaseprod" failed: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
rake aborted!
failed to execute:
pg_dump -s -x -O -f /home/user/app_path/db/structure.sql databaseprod

Please check the output above for any errors and make sure that `pg_dump` is installed in your PATH and has proper permissions.

/home/supercat/app_path/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/tasks/postgresql_database_tasks.rb:90:in `run_cmd'
/home/supercat/app_path/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/tasks/postgresql_database_tasks.rb:55:in `structure_dump'
/home/supercat/app_path/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:185:in `structure_dump'
/home/supercat/app_path/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:269:in `block (3 levels) in <top (required)>'
/home/supercat/app_path/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:53:in `block (2 levels) in <top (required)>'
/home/supercat/app_path/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
/home/supercat/app_path/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:structure:dump
(See full trace by running task with --trace)
```

## Workaround

My workaround is to modify `database.yml` as follows:

```yaml
---
production:
  encoding: unicode
  database: databaseprod
  username: user
  password: password
<% unless ENV["USE_MAKARA"] == "0" %>
  adapter: postgresql_makara
  makara:
    id: postgresql
    connections:
    - role: master
      host: masterdb.domain.com
    - role: standby
      host: standbydb.domain.com
<% else %>
  adapter: postgresql
  host: masterdb.domain.com
<% end %>
```

And then only run the `db:migrate` step as follows:
```
RAILS_ENV=production USE_MAKARA=0 bundle exec rake db:migrate
```
