### ISSUE TITLE
Makara::Errors::AllConnectionsBlacklisted

### ISSUE THREAD

**Issue by nikhilvs** [instacart/makara#78]
Issue looks like similar to #36 , but in our case we are not stopping any of our slave or master database.

Stack trace from new relic is as follows : 

….1/bundler/gems/makara-1ac718c7650c/lib/makara/
pool.rb:  95:in `provide'
…1/bundler/gems/makara-1ac718c7650c/lib/makara/
proxy.rb:  69:in`method_missing'
                         /usr/lib/ruby/1.9.1/
monitor.rb: 211:in `mon_synchronize'
                         /usr/lib/ruby/1.9.1/
monitor.rb: 211:in`mon_synchronize'
…_adapters/abstract/
connection_specification_changes.rb:  47:in `retrieve_connection'
…_adapters/abstract/
connection_specification_changes.rb:  29:in`connection'

What might have gone wrong in this case ?

Environment details
makara version  :  'v0.2.2' 
Rails version      :  3.2.14
Ruby version     :  ruby 1.9.3p484

**Comment by mnelson** [comment]
That error occurs when all connections had a failure related to connectivity within the blacklist duration. If you weren't using makara, it would be equivalent to seeing a connection error in newrelic. Are you able to provide the full trace and a summary of your database.yml?

**Comment by nikhilvs** [comment]
Our database.yml looks like this :

``` yml
  adapter: 'makara_mysql2'
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: <%= ENV['DB_POOL'] %>
  reaping_frequency: <%= ENV['REAPING_FREQUENCY'] %>
  timeout: 5000

  makara:
    blacklist_duration: 5
    master_ttl: 5
    sticky: true
    rescue_connection_failures: false

    connections:
      - role: master
        host: <%= ENV['RDS_HOSTNAME'] %>
        name: master-database
      - role: slave
        host: <%= ENV['DB_SLAVE1'] %>
        name: read-slave1
        weight: 5
      - role: slave
        host: <%= ENV['DB_SLAVE2'] %>
        name: read-slave2
        weight: 5
```

**Comment by joelr** [comment]
I get the same error when I only have one connection defined in the connection list, even when the connection is valid...

eg

```
    connections:
      - role: master
        host: <%= ENV['DATABASE_HOST'] %>
        adapter: mysql2
<% unless ENV['DATABASE_SLAVE_HOST'].blank? %>
      - role: slave
        host: <%= ENV['DATABASE_SLAVE_HOST'] %>
        adapter: mysql2
        database: <%= ENV['DATABASE_SLAVE_DATABASE'] %>
        username: <%= ENV['DATABASE_SLAVE_USERNAME'] %>
        password: <%= ENV['DATABASE_SLAVE_PASSWORD'] %>
<% end %>
```

I wanted the slave to be optional, but it seems to fail with Makara::Errors::AllConnectionsBlacklisted unless > 1 connection is defined, is this a known issue?
