### ISSUE TITLE
Support for master-master

### ISSUE THREAD

**Issue by robbertkl** [instacart/makara#85]
Currently, Makara does not support master-master clusters, like Galera, where the preferred way is to always write to only 1 specific member to avoid unnecessary deadlocks, but at the same time to distribute reads to _all_ cluster members for scalability.

In Makara, setting 1 of the cluster members as master, and the others as slave seems close to the solution. However, in case of failure of the member labeled as master, none of the other members (which are all labeled as slave) will take over the role of master.

**Comment by evantahler** [comment]
Perhaps Makara needs the ability to have a user-configurable function which can overwrite the default (round-robin) pool selection method.  This would solve this problem, and work generically for more esoteric use cases.. 

If you were able to do something like:

``` ruby
Makara::MasterSelector = lambda { | query, pools, config | 
  ...
  return pools[:master][0]
}

Makara::SlaveSelector = lambda { | query, pools, config | 
 ...
 return pools[:slave][0]
}
```

In your config, you could add additional content like:

``` yml
staging:
  adapter:  makara_mysql2
  database: myApp
  port:     3306

  makara:
    id: myApp
    blacklist_duration: 10
    master_ttl: 5
    sticky: true
    connections:
      - name:     master-1
        role:     master
        master_priority: 1 # <-------
        host:     123.123.123.123
      - name:     master-2
        role:     master
        master_priority: 2 # <-------
        host:     123.123.123.123

```

This would allow you to define custom logic to inspect the the servers in each pool, check if they were blacklisted or not, and make a choice based on `config.connections.master_priority`.

**Comment by robbertkl** [comment]
This would indeed make things way more flexible. It also helps for mutli data center replication, e.g. round-robin reads between _local_ cluster members, unless they're all blacklisted, then use _remote_ cluster members instead, as a last resort.

**Comment by mnelson** [comment]
So we're essentially talking about the pool object that already exists. https://github.com/taskrabbit/makara/blob/master/lib/makara/pool.rb#L86

The pool#provide methods can effectively be refactored to enable a simpler override. For instance, the master pool object could understand to choose the highest priority non-blacklisted connection, while the slave pool rotates like normal.

How about a config like this:

``` yml
staging:
  database: 'megadata'

  makara:

    master_node_selector: 'Makara::NodeSelectors::SingleWithFailover'
    slave_node_selector: 'Makara::NodeSelectors::RoundRobin'

    connections: 

      - name: 'master-1'
        role: 'master'
        priority: 1
        host: '111.1.1.111'

      - name: 'master-2'
        role: 'master'
        priority: 2
        host: '222.2.2.222'

      - name: 'slave-1'
        role: 'slave'
        host: '111.1.1.111'

      - name: 'slave-2'
        role: 'slave'
        host: '222.2.2.222'
```

The master / slave node selector configs would be class names. This would allow users to provide their own, rather than monkey-patching a built-in makara solution. Node selector objects would receive a pool (and all of it's connections) and decide how to effectively choose the "next" connection.

I'd like to handle the node selection at the pool level and allow makara to continue using the raw sql to choose between the master / slave pool.

Thoughts?
