### ISSUE TITLE
Server not being marked as blacklist

### ISSUE THREAD

**Issue by smikkelsen** [instacart/makara#92]
I have a master / slave configuration in makara

```
production:
  encoding: utf8
  reconnect: true
  pool: 20
  adapter: 'mysql2_makara'

  # add a makara subconfig
  makara:

    # the following are default values
    blacklist_duration: 5
    master_ttl: 5
    sticky: true

    # list your connections with the override values (they're merged into the top-level config)
    # be sure to provide the role if master, role is assumed to be a slave if not provided
    connections:
      - role: master
        host: IP ADDRESS
        database: DB NAME
        username: DB USER
        password: DB PASS
      - role: slave
        host: IP ADDRESS
        database: DB NAME
        username: DB USER
        password: DB PASS
```

If i stop mysql on the slave, I get an exception in rails: 

```
    Mysql2::Error (Can't connect to MySQL server on .....
```

Why aren't the reads failing over to the master in this case?

I also tried adding a custom matcher with no success:

```
  makara:
    blacklist_duration: 5
    master_ttl: 5
    sticky: true
    connection_error_matchers:
      - "/Mysql2::Error (Can't connect to MySQL server on/"
```

**Comment by yahya-hem** [comment]
I also have a similar master-slave setup and am facing the same issue. Please can someone comment on this?

**Comment by yahyapo** [comment]
I also have a similar setup and am facing the same issue. The reads are sometimes failing over to master and sometimes erring out with no specific pattern. Can someone comment on this please?

**Comment by mnelson** [comment]
@yahyapo do you also have reconnect=true in your database.yml?

**Comment by yahya-hem** [comment]
Yes, I have reconnect=true in the database.yml. This is how it looks :

default: &default
  adapter: mysql2_makara
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  username: <username>
  password: <password>
  host: 127.0.0.1
  makara:
      
      blacklist_duration: 5
      master_ttl: 5
      sticky: true

      connections:
        - role: master
          host: 127.0.0.1
        - role: slave
          host: <slave IP>

**Comment by yahya-hem** [comment]
@mnelson , any clue as to what is wrong?

**Comment by yahyapo** [comment]
Yes, I have reconnect=true in the database.yml. This is how it looks :

```
default: &default
adapter: mysql2_makara
pool: 5
timeout: 5000
encoding: utf8
reconnect: true
username: username
password: password
host: 127.0.0.1
makara:      
  blacklist_duration: 5
  master_ttl: 5
  sticky: true
  connections:
    - role: master
      host: 127.0.0.1
    - role: slave
      host: slave_ip
```
